### ISSUE TITLE
Refresh causes certain characters to not render properly

### ISSUE THREAD

**Issue by camspiers** [dsanson/termpdf.py#10]
When you hit ctrl+r, some new content that is added to the underlying pdf doesn't get rendered. 

In the following screenshot, you should be able to see how the T in "This" is missing.

<img width="2479" alt="Screen Shot 2020-04-16 at 8 25 21 PM" src="https://user-images.githubusercontent.com/51294/79432806-7052ba00-8020-11ea-8701-f20b152b859b.png">

**Comment by camspiers** [comment]
@dsanson You might appreciate the integration between Vimtex, Kitty and Termpdf.py here:

https://www.reddit.com/r/vim/comments/g2dfkt/back_with_more_vimtex_content_this_time_with_pdf/

Integration details here:

https://github.com/camspiers/dotfiles/blob/master/files/.config/kitty/termpdf.py

And here:

https://github.com/camspiers/dotfiles/blob/42316d7d1c14314e9851e1c92349ddb5662dc1b3/files/.config/nvim/init.vim#L608-L629

But note that in termpdf.py, the kitten that I am using to manage the opening and closing of termpdf.py I need to avoid using the "ctrl+r" approach for refreshing, because of the reported bug here:

https://github.com/camspiers/dotfiles/blob/42316d7d1c14314e9851e1c92349ddb5662dc1b3/files/.config/kitty/termpdf.py#L17-L21

**Comment by dsanson** [comment]
Neat! I need to look more at what you did to make a kitten. If I recall correctly, ctrl+r regenerates the image from the PDF page, and redraws the screen, but doesn't actually reload the PDF file itself. That is something that should be implemented!

**Comment by camspiers** [comment]
That is right, some but not all, it's quite strange. I did also notice that if your PDF grows in size, say from 1 page to 2, the count of the pages in the lower right isn't updated. Don't recall however whether you can access the second page.

**Comment by camspiers** [comment]
Basic fix is here #11

**Comment by camspiers** [comment]
Friendly ping :)

**Comment by dsanson** [comment]
The pull request has been merged. Does this fix the problem for everyone?

**Comment by camspiers** [comment]
It is fixed for me, thanks!
