### ISSUE TITLE
setup.py lacks  `roman`  dependency

### ISSUE THREAD

**Issue by teto** [dsanson/termpdf.py#3]
lacks the `roman` dep I think ?
```
@ setup.py:12 @ setup(name='termpdf.py',
      author_email='dsanson@gmail.com',
      url='https://github.com/dsanson/termpdf.py',
      scripts=['termpdf.py'],
      requires=['PyMuPDF', 'pyperclip']
      requires=['PyMuPDF', 'pyperclip', 'roman']
     )
```

**Comment by romain-fontugne** [comment]
For me this was missing in the requirements.txt:
roman
pdfrw
pagelabels

**Comment by teto** [comment]
would it be possible to move (or duplicate) the requirements to setup.py please ? it' the best way to distribute/install packages https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by dsanson** [comment]
Sorry. Should have up to date requirements.txt and setup.py now.
