### ISSUE TITLE
Toggling alpha transparency opens a new kitty window

### ISSUE THREAD

**Issue by slarwise** [dsanson/termpdf.py#9]
Hi and thanks so much for making this!

I am using kitty version 0.15.1 and termpdf version 0.1.1.

All shortcuts detailed in the README works for me except for toggling alpha transparency. When I press `a` a new kitty window opens. If I close this I get back to the previous window displaying the pdf but the transparency hasn't changed.

I am not using any config file for termpdf. Could the problem be related to the specification of KITTYCMD since a new window is opened?

EDIT: Looked through the code and found that the mapping was `A` rather than `a`. Pressing `A` toggles transparency fine!

**Comment by dsanson** [comment]
Right! 'a' was for 'annotate'. Not the best mappings.
